# Generated by Django 6.0.3 on 2026-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_carts', models.AutoField(primary_key=True, serialize=False)),
                ('id_users', models.IntegerField()),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id_cart_items', models.AutoField(primary_key=True, serialize=False)),
                ('id_carts', models.IntegerField()),
                ('id_products', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_categories', models.AutoField(primary_key=True, serialize=False)),
                ('name_categories', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_orders', models.AutoField(primary_key=True, serialize=False)),
                ('id_users', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_order_items', models.AutoField(primary_key=True, serialize=False)),
                ('id_orders', models.IntegerField()),
                ('id_products', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_products', models.AutoField(primary_key=True, serialize=False)),
                ('name_products', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_categories', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id_product_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_products', models.IntegerField()),
                ('socket', models.CharField(max_length=100, null=True)),
                ('cores', models.IntegerField(null=True)),
                ('threads', models.IntegerField(null=True)),
                ('base_clock', models.CharField(max_length=50, null=True)),
                ('memory_type', models.CharField(max_length=100, null=True)),
                ('capacity', models.CharField(max_length=100, null=True)),
                ('speed', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id_search_history', models.AutoField(primary_key=True, serialize=False)),
                ('id_users', models.IntegerField()),
                ('keyword_search_history', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('name_users', models.CharField(max_length=255)),
                ('email_users', models.CharField(max_length=255)),
                ('password_users', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id_user_behavior', models.AutoField(primary_key=True, serialize=False)),
                ('id_users', models.IntegerField()),
                ('id_products', models.IntegerField()),
                ('action_type_user_behavior', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_behavior',
            },
        ),
    ]
