# Generated by Django 6.0.3 on 2026-03-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False, 'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': False, 'verbose_name': 'Chi tiết giỏ hàng', 'verbose_name_plural': 'Chi tiết giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'managed': False, 'verbose_name': 'Thông số sản phẩm', 'verbose_name_plural': 'Thông số sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'managed': False, 'verbose_name': 'Lịch sử tìm kiếm', 'verbose_name_plural': 'Lịch sử tìm kiếm'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'managed': False, 'verbose_name': 'Hành vi người dùng', 'verbose_name_plural': 'Hành vi người dùng'},
        ),
    ]
