# Generated by Django 6.0.3 on 2026-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_recreate_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id_discounts', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('all', 'All')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'db_table': 'discounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Danh mục khuyến mãi',
                'verbose_name_plural': 'Danh mục khuyến mãi',
                'db_table': 'discount_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Sản phẩm khuyến mãi',
                'verbose_name_plural': 'Sản phẩm khuyến mãi',
                'db_table': 'discount_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_promotions', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.IntegerField()),
                ('used_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mã khuyến mãi',
                'verbose_name_plural': 'Mã khuyến mãi',
                'db_table': 'promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Sản phẩm áp dụng mã khuyến mãi',
                'verbose_name_plural': 'Sản phẩm áp dụng mã khuyến mãi',
                'db_table': 'promotion_products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False, 'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': False, 'verbose_name': 'Sản phẩm trong giỏ hàng', 'verbose_name_plural': 'Sản phẩm trong giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name': 'Sản phẩm trong đơn hàng', 'verbose_name_plural': 'Sản phẩm trong đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': False, 'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'managed': False, 'verbose_name': 'Lịch sử tìm kiếm', 'verbose_name_plural': 'Lịch sử tìm kiếm'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'managed': False, 'verbose_name': 'Hành vi người dùng', 'verbose_name_plural': 'Hành vi người dùng'},
        ),
    ]
