# Generated by Django 6.0.3 on 2026-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_discount_discountcategory_discountproduct_promotion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'managed': False, 'verbose_name': 'SALE', 'verbose_name_plural': 'SALE'},
        ),
        migrations.AlterModelOptions(
            name='discountcategory',
            options={'managed': False, 'verbose_name': 'Danh mục SALE', 'verbose_name_plural': 'Danh mục SALE'},
        ),
        migrations.AlterModelOptions(
            name='discountproduct',
            options={'managed': False, 'verbose_name': 'Sản phẩm SALE', 'verbose_name_plural': 'Sản phẩm SALE'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'managed': False, 'verbose_name': 'Mã giảm giá', 'verbose_name_plural': 'Mã giảm giá'},
        ),
        migrations.AlterModelOptions(
            name='promotionproduct',
            options={'managed': False, 'verbose_name': 'Sản phẩm áp dụng mã giảm giá', 'verbose_name_plural': 'Sản phẩm áp dụng mã giảm giá'},
        ),
    ]
