# Generated by Django 6.0.3 on 2026-04-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
            ],
            options={
                'verbose_name': 'Độ tương đồng sản phẩm',
                'verbose_name_plural': 'Độ tương đồng sản phẩm',
                'db_table': 'item_similarity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
            options={
                'verbose_name': 'Điểm user-sản phẩm',
                'verbose_name_plural': 'Điểm user-sản phẩm',
                'db_table': 'user_item_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id_user_promotions', models.AutoField(primary_key=True, serialize=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('used_count', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá của người dùng',
                'verbose_name_plural': 'Mã giảm giá của người dùng',
                'db_table': 'user_promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
            ],
            options={
                'verbose_name': 'Độ tương đồng người dùng',
                'verbose_name_plural': 'Độ tương đồng người dùng',
                'db_table': 'user_similarity',
                'managed': False,
            },
        ),
    ]
