# Generated by Django 6.0.3 on 2026-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_itemsimilarity_useritemscore_userpromotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id_user_addresses', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_address', models.CharField(max_length=255)),
                ('phone_address', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at_addresses', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Địa chỉ người dùng',
                'verbose_name_plural': 'Địa chỉ người dùng',
                'db_table': 'user_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id_settings', models.AutoField(primary_key=True, serialize=False)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_url', models.CharField(blank=True, max_length=500, null=True)),
                ('website_name', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_about', models.CharField(blank=True, max_length=1000, null=True)),
                ('footer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('footer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt website',
                'verbose_name_plural': 'Cài đặt website',
                'db_table': 'website_settings',
                'managed': False,
            },
        ),
    ]
