
"""
Django settings for pc_ai_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

GEMINI_API_KEY = "AIzaSyCFGnJ8Efxx8iRZ7ic4MAKpsznnkFZlv1w"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-41cpywa%hjv4w3*omei2j_fg02a6hnjj$o9(r&iu&6=gtpdj+)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pc_ai_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'store' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pc_ai_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'pc_store_1',
        'HOST': 'Admin-PC\\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    },
    'chatbot': {
        'ENGINE': 'mssql',
        'NAME': 'pc_store_1',
        'HOST': 'Admin-PC\\SQLEXPRESS',
        'PORT': '',
        'USER': 'chatbot_user',
        'PASSWORD': 'Chatbot123@',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'laitrongcanh2504@gmail.com')
# Gmail App Password thường được hiển thị theo nhóm 4 ký tự, nhưng khi cấu hình SMTP phải dùng chuỗi liền.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'vlqt faia xvon hfpo').replace(' ', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR.parent.parent,
]


JAZZMIN_SETTINGS = {
    "site_title": "LTC Computer",
    "site_header": "LTC Computer",
    "site_brand": ".",
    "site_url": "/",
    "site_logo": "logo1.png",
    "login_logo": "logo1.png",
    "site_logo_classes": "img-circle elevation-2",
    "welcome_sign": "Chào mừng đến với LTC Computer",
    "copyright": "LTC Computer",
    # "search_model": ["store.Product"],
    "topmenu_links": [
        {"name": "Trang quản trị", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "store.Product"},
        {"model": "store.Order"},
        {"model": "store.WebsiteSettings"},
        {"app": "store"},
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "store.User": "fas fa-user",
        "store.UserAddress": "fas fa-map-marker-alt",
        "store.Category": "fas fa-layer-group",
        "store.Product": "fas fa-microchip",
        "store.ProductDetail": "fas fa-list-alt",
        "store.Cart": "fas fa-shopping-cart",
        "store.CartItem": "fas fa-cart-plus",
        "store.Discount": "fas fa-tags",
        "store.DiscountCategory": "fas fa-object-group",
        "store.DiscountProduct": "fas fa-box-open",
        "store.Promotion": "fas fa-ticket-alt",
        "store.PromotionProduct": "fas fa-gift",
        "store.Order": "fas fa-file-invoice",
        "store.OrderItem": "fas fa-receipt",
        "store.UserBehavior": "fas fa-chart-line",
        "store.SearchHistory": "fas fa-search",
        "store.WebsiteSettings": "fas fa-cog",
    },
    "order_with_respect_to": [
        "store.Category",
        "store.User",
        "store.UserAddress",
        "store.Product",
        "store.Order",
        "store.Promotion",
        "store.Discount",
        "store.PromotionProduct",
        "store.DiscountCategory",
        "store.DiscountProduct",
        "store.ProductDetail",
        "store.Cart",
        "store.SearchHistory",
        "store.UserBehavior",
        "store.WebsiteSettings",
    ],
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    "custom_css": "store/admin/admin_theme_v4.css?v=20260410d",
    "custom_js": "store/admin/admin_theme_v4.js?v=20260410d",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    # "dark_mode_theme": None,
    # "navbar": "navbar-white navbar-light",
    "accent": "accent-primary",
    "navbar_small_text": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    # "theme_switcher": False,  
}

# MEDIA FILES CONFIGURATION
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'product_image')


# VNPAY SANDBOX CONFIGURATION
VNPAY_TMN_CODE = os.environ.get('VNPAY_TMN_CODE', 'K8117APR')
VNPAY_HASH_SECRET = os.environ.get('VNPAY_HASH_SECRET', 'MDCOTJ8JNE3TN4YN3PWL6BYB1TN69WUJ')
VNPAY_PAYMENT_URL = os.environ.get('VNPAY_PAYMENT_URL', 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html')
VNPAY_RETURN_URL = os.environ.get('VNPAY_RETURN_URL', 'http://127.0.0.1:8000/api/payment/vnpay-return/')
